# Hierachical (Multi-) Indexing
* Contact: Lachlan Deer, [econgit] @ldeer, [github/twitter] @lachlandeer

In earlier notebooks we were working with our labor market data and importing it to have a multi-index. In this notebook, we explore the notions of multi-indexing in more detail.

In [1]:
import pandas as pd

## Multiply Indexed Data

We focus on multiply indexed `DataFrames`, and ignore pandas `Series` because we will most often come across `DataFrames`. Most of our discussion carries over.

Let's import our labour market data in the 'simplest way'

In [7]:
data = pd.read_csv('out_data/state_labour_statistics.csv')
data.head()

,state,period,year,unemployment_rate,qty_unemployed,qty_employed,labour_force
0,Alabama,M01,2000,5.1,108551,2024262,2132813
1,Alabama,M01,2001,5.2,110035,2008876,2118911
2,Alabama,M01,2002,6.5,134750,1953814,2088564
3,Alabama,M01,2003,6.2,129966,1974374,2104340
4,Alabama,M01,2004,6.4,134673,1985886,2120559

In [3]:
data.index

RangeIndex(start=0, stop=10608, step=1)

Again note that pandas has created an index for us, which is simply a row identifier. We argued earlier that a better way of indexing might be state-year-month. 

To make the shift to our preferred index, we need to reset the index, using the `set_index` function.

In [11]:
data.set_index(['state', 'year', 'period'], inplace=True)
data.head()

                     unemployment_rate  qty_unemployed  qty_employed  \
state   year period
Alabama 2000 M01                   5.1          108551       2024262
        2001 M01                   5.2          110035       2008876
        2002 M01                   6.5          134750       1953814
        2003 M01                   6.2          129966       1974374
        2004 M01                   6.4          134673       1985886

                     labour_force
state   year period
Alabama 2000 M01          2132813
        2001 M01          2118911
        2002 M01          2088564
        2003 M01          2104340
        2004 M01          2120559

If we want to go back to the original index, we can use `reset_index` and ask that the multi-index we set is returned to columns of the data

In [13]:
data.reset_index(drop=False, inplace=True)

In [14]:
data.head()

,state,year,period,unemployment_rate,qty_unemployed,qty_employed,labour_force
0,Alabama,2000,M01,5.1,108551,2024262,2132813
1,Alabama,2001,M01,5.2,110035,2008876,2118911
2,Alabama,2002,M01,6.5,134750,1953814,2088564
3,Alabama,2003,M01,6.2,129966,1974374,2104340
4,Alabama,2004,M01,6.4,134673,1985886,2120559

But let's for now stick with our multi-index data- and see how to use it

In [15]:
data.set_index(['state', 'year', 'period'], inplace=True)

## Selecting Data with a Multi-Index

One advantage of a multi-index is that we can subset data quite simply:

In [18]:
data.loc['Alabama']

             unemployment_rate  qty_unemployed  qty_employed  labour_force
year period
2000 M01                   5.1          108551       2024262       2132813
2001 M01                   5.2          110035       2008876       2118911
2002 M01                   6.5          134750       1953814       2088564
2003 M01                   6.2          129966       1974374       2104340
2004 M01                   6.4          134673       1985886       2120559
2005 M01                   5.4          114319       2011219       2125538
2006 M01                   4.4           93680       2048878       2142558
2007 M01                   4.3           93046       2076252       2169298
2008 M01                   4.8          104650       2065583       2170233
2009 M01                   9.7          208908       1955196       2164104
2010 M01                  12.3          263375       1871780       2135155
2011 M01                  11.0          243001       1967127       2210128
2012 M01                   8.3          177986       1973652       2151638
2013 M01                   8.2          177887       1988180       2166067
2014 M01                   7.5          162341       1989459       2151800
2015 M01                   6.4          135842       1998388       2134230
2016 M01                   6.3          134592       2007036       2141628
2000 M02                   5.1          109464       2027226       2136690
2001 M02                   5.0          105469       2009904       2115373
2002 M02                   6.3          132979       1966562       2099541
2003 M02                   6.0          127265       1980206       2107471
2004 M02                   6.1          130294       1990082       2120376
2005 M02                   5.4          115837       2014928       2130765
2006 M02                   4.5           96643       2053723       2150366
2007 M02                   4.2           91769       2078300       2170069
2008 M02                   4.9          106990       2060564       2167554
2009 M02                  10.5          227822       1943707       2171529
2010 M02                  12.1          258825       1876758       2135583
2011 M02                  10.5          232117       1972720       2204837
2012 M02                   8.4          182555       1982828       2165383
...                        ...             ...           ...           ...
2004 M11                   5.2          111612       2043152       2154764
2005 M11                   4.0           86786       2078869       2165655
2006 M11                   3.7           80347       2105333       2185680
2007 M11                   3.9           85214       2107374       2192588
2008 M11                   6.7          145764       2030180       2175944
2009 M11                  11.1          238550       1910326       2148876
2010 M11                  10.0          222536       2001481       2224017
2011 M11                   8.0          175369       2008604       2183973
2012 M11                   6.9          149468       2023318       2172786
2013 M11                   6.7          144052       2020314       2164366
2014 M11                   5.8          124177       2033698       2157875
2015 M11                   5.7          122954       2035229       2158183
2016 M11                   5.7          123834       2060807       2184641
2000 M12                   4.2           90116       2045059       2135175
2001 M12                   5.8          124127       1998822       2122949
2002 M12                   5.7          121340       2001747       2123087
2003 M12                   5.7          121278       2012259       2133537
2004 M12                   4.9          105756       2041339       2147095
2005 M12                   3.9           83794       2079724       2163518
2006 M12                   3.7           82045       2107748       2189793
2007 M12                   4.3           93382       2096601       2189983
2008 M12                   7.6          164258       2008873       2173131
2009 M12                  11.4          242992       1894973       2137965
2010 M12                   9.8          217272       1996538       2213810
2011 M12                   7.9          172004       2004151       2176155
2012 M12                   7.2          156518       2016210       2172728
2013 M12                   6.7          143618       2013519       2157137
2014 M12                   5.7          121281       2023427       2144708
2015 M12                   5.9          127389       2030765       2158154
2016 M12                   5.9          129295       2050965       2180260

[204 rows x 4 columns]

In [24]:
data.loc['Alabama', 2010]

/home/lachlan/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  if __name__ == '__main__':

        unemployment_rate  qty_unemployed  qty_employed  labour_force
period
M01                  12.3          263375       1871780       2135155
M02                  12.1          258825       1876758       2135583
M03                  11.5          245567       1892006       2137573
M04                  10.4          229680       1976552       2206232
M05                   9.9          219339       1994090       2213429
M06                  10.5          234972       1994590       2229562
M07                  10.2          225826       1990949       2216775
M08                  10.1          224435       1988261       2212696
M09                   9.8          216750       1990219       2206969
M10                   9.9          219224       2001483       2220707
M11                  10.0          222536       2001481       2224017
M12                   9.8          217272       1996538       2213810

In [25]:
data.loc['Alabama', 2010, 'M10']

unemployment_rate          9.9
qty_unemployed        219224.0
qty_employed         2001483.0
labour_force         2220707.0
Name: (Alabama, 2010, M10), dtype: float64

In [28]:
# we hope this may work...
data.loc['Alabama', :, 'M10']

KeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (3), lexsort depth (1)'

In [30]:
# we need to sort the index first
data = data.sort_index()
data.head()

                     unemployment_rate  qty_unemployed  qty_employed  \
state   year period
Alabama 2000 M01                   5.1          108551       2024262
             M02                   5.1          109464       2027226
             M03                   4.5           95449       2038654
             M04                   3.8           80215       2045171
             M05                   4.1           86308       2037787

                     labour_force
state   year period
Alabama 2000 M01          2132813
             M02          2136690
             M03          2134103
             M04          2125386
             M05          2124095

In [33]:
data.loc['Alabama', 2010:2016, 'M10':'M12']

                     unemployment_rate  qty_unemployed  qty_employed  \
state   year period
Alabama 2010 M10                   9.9          219224       2001483
             M11                  10.0          222536       2001481
             M12                   9.8          217272       1996538
        2011 M10                   8.9          194917       2005689
             M11                   8.0          175369       2008604
             M12                   7.9          172004       2004151
        2012 M10                   7.5          165164       2025114
             M11                   6.9          149468       2023318
             M12                   7.2          156518       2016210
        2013 M10                   7.0          152300       2012001
             M11                   6.7          144052       2020314
             M12                   6.7          143618       2013519
        2014 M10                   6.0          130881       2035345
             M11                   5.8          124177       2033698
             M12                   5.7          121281       2023427
        2015 M10                   5.9          126424       2032455
             M11                   5.7          122954       2035229
             M12                   5.9          127389       2030765
        2016 M10                   6.2          136336       2057151
             M11                   5.7          123834       2060807
             M12                   5.9          129295       2050965

                     labour_force
state   year period
Alabama 2010 M10          2220707
             M11          2224017
             M12          2213810
        2011 M10          2200606
             M11          2183973
             M12          2176155
        2012 M10          2190278
             M11          2172786
             M12          2172728
        2013 M10          2164301
             M11          2164366
             M12          2157137
        2014 M10          2166226
             M11          2157875
             M12          2144708
        2015 M10          2158879
             M11          2158183
             M12          2158154
        2016 M10          2193487
             M11          2184641
             M12          2180260

### Challenge

1. Extract all the data for the Carolinas (Help: you need to do a partial string match on the index `data.index.get_level_values(XX).str.contains(YY)` )
2. Extract all the data for the Carolinas in 2007
3. Extract all the data for the Carolinas between 2007-2010
4. Extract all the data in the summer months for the Carolina between 2007 and 2010

#### Partial Solution:

In [42]:
data.loc[data.index.get_level_values(0).str.contains("Carolina"), 
             2007:2010, 'M06':'M09']

                            unemployment_rate  qty_unemployed  qty_employed  \
state          year period
North Carolina 2007 M06                   4.9          220499       4323332
                    M07                   5.1          231083       4336375
                    M08                   4.7          212508       4299171
                    M09                   4.5          201890       4321920
               2008 M06                   5.9          271173       4313781
                    M07                   6.3          289018       4324163
                    M08                   6.3          288553       4282651
                    M09                   5.9          268607       4292928
               2009 M06                  10.8          498908       4102835
                    M07                  10.8          498541       4121528
                    M08                  10.6          485802       4083402
                    M09                  10.4          472231       4076322
               2010 M06                  10.9          503871       4137291
                    M07                  10.8          503704       4150739
                    M08                  10.5          486253       4137732
                    M09                  10.0          459133       4152584
South Carolina 2007 M06                   5.9          126476       2033179
                    M07                   5.8          125358       2031889
                    M08                   5.7          121989       2015875
                    M09                   5.6          119816       2008234
               2008 M06                   6.6          143842       2028477
                    M07                   6.9          149774       2022393
                    M08                   7.5          162877       2003086
                    M09                   7.5          160318       1990871
               2009 M06                  11.9          260682       1932513
                    M07                  11.6          253471       1932518
                    M08                  11.5          247965       1914687
                    M09                  11.5          245694       1895141
               2010 M06                  11.2          244208       1940423
                    M07                  11.0          240106       1944223
                    M08                  11.2          244749       1934786
                    M09                  10.7          231578       1923986

                            labour_force
state          year period
North Carolina 2007 M06          4543831
                    M07          4567458
                    M08          4511679
                    M09          4523810
               2008 M06          4584954
                    M07          4613181
                    M08          4571204
                    M09          4561535
               2009 M06          4601743
                    M07          4620069
                    M08          4569204
                    M09          4548553
               2010 M06          4641162
                    M07          4654443
                    M08          4623985
                    M09          4611717
South Carolina 2007 M06          2159655
                    M07          2157247
                    M08          2137864
                    M09          2128050
               2008 M06          2172319
                    M07          2172167
                    M08          2165963
                    M09          2151189
               2009 M06          2193195
                    M07          2185989
                    M08          2162652
                    M09          2140835
               2010 M06          2184631
                    M07          2184329
                    M08          2179535
                    M09          2155564

## Index (Un-)Stacking

One potentially cool use for multi-indexing is using the indexes across *two* dimensions. This is *unstacking*, and often allows for simple ways to view patterns in the data.

For example, we could translate the year-index across to a column axis, so that we could can easily see patterns in labor force statistics in a given month, but over various years:

In [49]:
data.unstack(level=1)

                     unemployment_rate                                     \
year                              2000 2001 2002 2003 2004 2005 2006 2007
state         period
Alabama       M01                  5.1  5.2  6.5  6.2  6.4  5.4  4.4  4.3
              M02                  5.1  5.0  6.3  6.0  6.1  5.4  4.5  4.2
              M03                  4.5  4.7  6.0  5.6  5.9  4.6  3.9  3.8
              M04                  3.8  4.2  5.3  5.3  5.2  3.9  3.5  3.3
              M05                  4.1  4.0  5.2  5.6  5.4  4.0  3.6  3.3
              M06                  4.9  5.2  6.3  6.9  6.1  5.0  4.6  4.2
              M07                  4.9  5.1  6.2  6.3  6.0  4.7  4.6  4.4
              M08                  5.0  5.6  6.2  6.4  5.9  4.5  4.4  4.3
              M09                  4.5  5.3  5.7  6.0  5.6  4.3  3.9  4.0
              M10                  4.5  5.6  5.6  6.1  5.5  4.2  3.6  3.8
              M11                  4.4  5.8  5.8  6.1  5.2  4.0  3.7  3.9
              M12                  4.2  5.8  5.7  5.7  4.9  3.9  3.7  4.3
Alaska        M01                  7.4  7.5  7.8  8.7  8.8  8.1  7.9  7.3
              M02                  7.5  7.4  8.0  9.0  8.9  8.2  7.9  7.3
              M03                  7.2  7.1  8.0  8.7  8.5  7.7  7.5  7.1
              M04                  6.7  6.7  7.6  8.2  7.8  7.0  7.0  6.5
              M05                  6.4  6.4  7.2  7.7  7.4  6.7  6.6  6.2
              M06                  6.4  6.5  7.4  7.9  7.6  6.8  6.5  6.4
              M07                  5.5  5.6  6.6  7.1  6.5  6.0  5.8  5.6
              M08                  5.2  5.3  6.3  6.7  6.2  5.7  5.5  5.4
              M09                  5.6  5.5  6.6  6.9  6.5  6.0  5.7  5.6
              M10                  5.8  5.9  6.9  7.2  6.8  6.4  6.0  5.8
              M11                  6.3  6.5  7.4  7.8  7.2  6.9  6.4  6.3
              M12                  6.5  6.8  7.7  8.0  7.3  7.1  6.6  6.5
Arizona       M01                  4.2  4.3  6.1  6.1  5.5  4.9  4.5  4.1
              M02                  3.9  3.9  5.7  5.8  5.1  4.7  4.4  3.7
              M03                  3.9  4.1  5.9  5.7  5.2  4.7  4.2  3.6
              M04                  3.6  4.1  5.9  5.6  5.1  4.6  4.1  3.5
              M05                  3.8  4.1  5.9  5.6  4.9  4.4  4.0  3.4
              M06                  4.3  5.0  6.5  6.3  5.4  4.9  4.5  3.8
...                                ...  ...  ...  ...  ...  ...  ...  ...
West Virginia M07                  5.1  4.6  5.8  6.1  5.1  5.1  5.2  4.5
              M08                  5.2  4.7  5.7  6.0  5.1  5.1  5.3  4.6
              M09                  4.8  4.2  5.3  5.3  4.4  4.7  4.7  4.2
              M10                  4.8  4.2  5.2  5.1  4.4  4.4  4.3  4.0
              M11                  5.0  4.6  5.5  5.1  4.5  4.4  4.3  4.0
              M12                  5.1  4.8  5.7  5.2  4.7  4.3  4.2  4.3
Wisconsin     M01                  3.8  4.5  6.1  6.4  6.0  5.5  5.2  5.5
              M02                  4.2  5.1  6.5  6.8  6.3  5.9  5.8  6.0
              M03                  4.2  5.1  6.4  6.7  6.3  5.5  5.6  5.6
              M04                  3.4  4.6  5.7  6.0  5.3  4.8  4.9  5.2
              M05                  3.3  4.1  5.0  5.5  4.9  4.5  4.5  4.7
              M06                  3.9  4.8  5.6  6.2  5.3  4.9  4.9  5.1
              M07                  3.7  4.4  5.3  5.8  4.9  4.6  4.7  4.9
              M08                  3.5  4.3  5.0  5.5  4.6  4.3  4.5  4.7
              M09                  3.0  3.9  4.5  5.0  4.1  4.1  4.1  4.3
              M10                  2.8  4.1  4.4  4.7  4.0  3.9  3.9  4.1
              M11                  3.2  4.6  4.9  4.9  4.2  4.4  4.3  4.2
              M12                  3.3  4.8  5.1  4.9  4.4  4.5  4.5  4.5
Wyoming       M01                  5.1  4.8  4.8  5.4  4.9  4.4  4.1  3.5
              M02                  4.7  4.4  4.5  5.1  4.5  4.0  3.7  3.2
              M03                  4.4  4.4  4.6  5.0  4.3  3.9  3.6  3.2
              M04                  3.9  3.8  4.2  4.5  3.8  3.5  3.2  3.0
              M05                  3.6  3.6  3.8  4.1  3.6  3.5  3.1  2.8
              M06                  3.7  3.8  3.9  4.2  3.7  3.7  3.2  3.0
              M07                  3.4  3.4  3.5  3.8  3.4  3.3  2.9  2.7
              M08                  3.4  3.3  3.4  3.7  3.3  3.2  2.8  2.5
              M09                  3.4  3.3  3.5  3.6  3.4  3.2  2.8  2.4
              M10                  3.4  3.4  3.6  3.6  3.4  3.3  2.8  2.4
              M11                  4.0  3.8  4.2  4.1  3.7  3.5  3.0  2.6
              M12                  3.9  3.9  4.5  4.2  3.7  3.5  2.9  2.5

                                  ...    labour_force                    \
year                 2008  2009   ...            2007     2008     2009
state         period              ...
Alabama       M01     4.8   9.7   ...         2169298  2170233  2164104
              M02     4.9  10.5   ...         2170069  2167554  2171529
              M03     4.7  10.4   ...         2176156  2170499  2166423
              M04     4.0   9.9   ...         2156839  2162674  2162016
              M05     4.9  10.6   ...         2158625  2174485  2164803
              M06     5.9  11.9   ...         2184718  2195259  2189836
              M07     6.0  11.8   ...         2182352  2192307  2178713
              M08     6.2  11.9   ...         2170686  2180770  2166591
              M09     5.9  11.5   ...         2174850  2169953  2146406
              M10     6.3  11.7   ...         2181178  2185049  2158726
              M11     6.7  11.1   ...         2192588  2175944  2148876
              M12     7.6  11.4   ...         2189983  2173131  2137965
Alaska        M01     7.4   8.0   ...          345579   349267   353287
              M02     7.6   8.3   ...          346089   350568   354740
              M03     7.3   8.3   ...          346333   351093   355085
              M04     6.9   7.9   ...          345090   350951   355025
              M05     6.6   7.7   ...          350961   357618   360406
              M06     6.7   7.9   ...          357854   364161   367342
              M07     6.0   7.1   ...          361263   367756   370991
              M08     5.8   6.9   ...          356641   362908   366043
              M09     5.9   7.2   ...          351903   357059   360500
              M10     6.3   7.6   ...          349686   354710   358511
              M11     6.8   8.0   ...          349338   353954   357869
              M12     7.0   8.0   ...          348689   353273   355967
Arizona       M01     4.7   8.5   ...         3023595  3061807  3116556
              M02     4.5   8.6   ...         3019018  3055475  3120236
              M03     4.7   8.9   ...         3022680  3065528  3115010
              M04     4.7   8.9   ...         3008613  3072584  3126747
              M05     5.4   9.3   ...         3006195  3080441  3119101
              M06     6.1  10.1   ...         3034911  3113462  3144544
...                   ...   ...   ...             ...      ...      ...
West Virginia M07     3.9   8.0   ...          821068   819438   825970
              M08     3.9   8.0   ...          814483   812898   818198
              M09     3.6   7.5   ...          817313   815060   815372
              M10     3.7   7.6   ...          816779   816165   814200
              M11     4.0   7.6   ...          813431   809560   808199
              M12     4.7   8.1   ...          807619   803663   800282
Wisconsin     M01     5.2   7.7   ...         3060928  3065592  3085078
              M02     5.5   8.8   ...         3074766  3069763  3105799
              M03     5.2   9.3   ...         3070414  3067047  3100095
              M04     4.5   8.7   ...         3067071  3069620  3099413
              M05     4.3   8.5   ...         3068194  3072305  3099673
              M06     4.8   9.0   ...         3136599  3133022  3158079
              M07     4.7   8.8   ...         3135103  3135749  3152753
              M08     4.7   8.6   ...         3103563  3112870  3122068
              M09     4.3   8.1   ...         3088638  3089165  3076468
              M10     4.5   8.2   ...         3083927  3100099  3074584
              M11     5.2   8.3   ...         3086014  3095403  3070326
              M12     6.0   8.9   ...         3078715  3090917  3059841
Wyoming       M01     3.7   5.2   ...          280655   287962   294670
              M02     3.4   5.5   ...          280755   288225   294997
              M03     3.4   6.3   ...          282920   289456   297893
              M04     3.0   6.8   ...          282916   289203   299650
              M05     2.7   6.5   ...          284791   290627   300307
              M06     3.0   6.7   ...          292137   298014   305996
              M07     2.7   6.3   ...          292045   298278   304603
              M08     2.6   6.1   ...          290133   296658   302187
              M09     2.5   6.0   ...          287821   294561   299774
              M10     2.7   6.3   ...          288442   295880   300205
              M11     3.2   6.7   ...          288931   295690   300575
              M12     3.7   7.5   ...          287174   294792   300582

                                                                            \
year                     2010     2011     2012     2013     2014     2015
state         period
Alabama       M01     2135155  2210128  2151638  2166067  2151800  2134230
              M02     2135583  2204837  2165383  2170603  2165104  2136284
              M03     2137573  2206650  2171589  2164327  2172369  2139776
              M04     2206232  2204162  2163833  2158996  2153646  2144272
              M05     2213429  2205918  2178571  2171580  2164055  2162423
              M06     2229562  2221913  2203489  2188077  2181034  2170213
              M07     2216775  2213352  2195941  2180234  2179484  2166130
              M08     2212696  2202727  2177294  2167203  2161076  2154821
              M09     2206969  2201614  2172512  2168032  2151252  2144102
              M10     2220707  2200606  2190278  2164301  2166226  2158879
              M11     2224017  2183973  2172786  2164366  2157875  2158183
              M12     2213810  2176155  2172728  2157137  2144708  2158154
Alaska        M01      356118   360755   361338   360146   361268   359313
              M02      357061   361511   362206   360707   361940   359707
              M03      357402   361503   362360   360341   362052   359477
              M04      356659   360268   360842   359701   361485   358214
              M05      361477   365295   366292   365543   367332   364021
              M06      368539   372776   372708   372251   373662   370528
              M07      372360   376479   375658   375567   377041   373613
              M08      367761   372217   370567   371313   371586   368155
              M09      363039   367706   365772   366534   366000   362931
              M10      360922   364639   364223   363324   362629   360163
              M11      360864   364224   362601   362911   361195   358575
              M12      360758   363580   361654   361373   359599   357258
Arizona       M01     3107217  3039415  3012695  3016658  3050414  3136757
              M02     3105393  3035196  3020747  3013596  3060686  3137774
              M03     3097065  3036772  3021250  3010932  3075747  3137770
              M04     3113311  3033931  3017136  3019931  3064021  3148501
              M05     3091206  3022263  3024215  3027720  3074731  3158989
              M06     3096351  3056961  3043976  3051207  3100928  3169400
...                       ...      ...      ...      ...      ...      ...
West Virginia M07      816453   808138   816043   806468   795817   794186
              M08      814502   809132   810068   800613   789203   787186
              M09      816165   811911   812127   799428   786872   782634
              M10      813557   811912   813548   797058   788898   783633
              M11      808559   805724   804246   791811   779068   777074
              M12      804033   801402   799724   786333   772321   773280
Wisconsin     M01     3061794  3055772  3042800  3057850  3048638  3068152
              M02     3077511  3070527  3062856  3069631  3067050  3077954
              M03     3077035  3069038  3057206  3058221  3068174  3070504
              M04     3078882  3062326  3050793  3068832  3057426  3068174
              M05     3074285  3069458  3068660  3073725  3069533  3089419
              M06     3120226  3121897  3125920  3134678  3124992  3135247
              M07     3118308  3117197  3116391  3130827  3129343  3131648
              M08     3102723  3100780  3084960  3100786  3106267  3109477
              M09     3072257  3079559  3066629  3083361  3088257  3089177
              M10     3069318  3078481  3076594  3071460  3097880  3100845
              M11     3066617  3069857  3068600  3076073  3090025  3100885
              M12     3059191  3062217  3066357  3066070  3073486  3096798
Wyoming       M01      299388   303903   305451   303988   304065   302808
              M02      299182   303474   304974   303316   303633   302822
              M03      300782   304846   306071   304385   304626   304636
              M04      301054   304293   305671   304429   304608   304429
              M05      302103   304630   305878   304599   305415   305204
              M06      307449   310674   312119   311450   311972   311380
              M07      306184   310751   311440   310830   311218   310245
              M08      305471   309004   309559   308650   308852   307846
              M09      303557   307206   306748   306052   306169   304353
              M10      304878   307938   307263   306560   306735   304311
              M11      305384   308172   306948   306599   306418   302892
              M12      304124   306890   305084   305285   303753   300859


year                     2016
state         period
Alabama       M01     2141628
              M02     2152446
              M03     2160907
              M04     2154477
              M05     2159095
              M06     2177701
              M07     2173465
              M08     2168460
              M09     2176728
              M10     2193487
              M11     2184641
              M12     2180260
Alaska        M01      356376
              M02      357339
              M03      357230
              M04      356340
              M05      361669
              M06      367755
              M07      371272
              M08      366325
              M09      360761
              M10      357474
              M11      356778
              M12      355793
Arizona       M01     3197977
              M02     3214959
              M03     3223314
              M04     3220117
              M05     3220802
              M06     3239204
...                       ...
West Virginia M07      791694
              M08      787513
              M09      787174
              M10      788123
              M11      779129
              M12      771785
Wisconsin     M01     3084452
              M02     3106527
              M03     3103663
              M04     3098029
              M05     3106700
              M06     3164710
              M07     3164480
              M08     3144447
              M09     3127214
              M10     3127427
              M11     3116760
              M12     3098335
Wyoming       M01      300160
              M02      299963
              M03      301721
              M04      301994
              M05      302387
              M06      308256
              M07      306926
              M08      304511
              M09      301548
              M10      300979
              M11      300414
              M12      299114

[624 rows x 68 columns]

In it's current form this is a bit ugly because there is so much data. But we can use our indexing function `loc` together with a column selection to potentially view one of our series:

In [52]:
data.unstack(level=1).loc['California']['unemployment_rate']

year,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
period,,,,,,,,,,,,,,,,,
M01,5.4,5.3,7.0,7.3,7.0,6.2,5.3,5.5,6.4,10.2,12.7,12.6,11.4,10.2,8.4,7.2,5.9
M02,5.4,5.1,6.8,7.1,6.7,6.1,5.3,5.4,6.3,10.6,12.6,12.2,11.3,9.7,8.4,6.9,5.8
M03,5.4,5.3,6.9,7.1,7.0,5.9,5.2,5.2,6.6,10.9,12.6,12.1,11.0,9.3,8.3,6.7,5.8
M04,4.8,4.9,6.6,6.7,6.3,5.3,4.9,5.0,6.1,10.4,12.0,11.5,10.3,8.7,7.3,6.2,5.4
M05,4.8,4.6,6.2,6.4,5.9,5.0,4.5,4.8,6.4,10.6,11.7,11.3,10.2,8.6,7.2,6.1,4.9
M06,5.0,5.2,6.7,7.2,6.4,5.4,4.9,5.3,7.0,11.3,12.0,12.0,10.6,9.2,7.4,6.3,5.6
M07,5.3,5.5,6.9,7.1,6.4,5.5,5.2,5.7,7.6,11.7,12.6,12.2,10.9,9.3,7.9,6.5,5.8
M08,5.0,5.7,6.7,6.8,5.9,5.1,4.9,5.4,7.8,11.5,12.3,11.9,10.4,8.9,7.6,6.1,5.6
M09,4.6,5.5,6.3,6.5,5.6,5.1,4.6,5.3,7.7,11.4,11.9,11.5,9.6,8.5,7.0,5.6,5.2
M10,4.5,5.8,6.4,6.5,5.7,5.0,4.5,5.4,8.0,11.6,11.9,11.3,9.7,8.5,6.9,5.7,5.2
M11,4.7,6.2,6.8,6.7,5.9,5.3,4.8,5.6,8.4,11.7,12.3,11.0,9.5,8.3,7.0,5.7,5.0
M12,4.4,6.1,6.7,6.2,5.7,4.9,4.7,5.9,9.0,11.8,12.1,11.0,9.6,8.0,6.6,5.6,5.0

the opposite of unstacking is `stacking`, and it puts our data back into the multi-index format we began with:

In [50]:
data.unstack(level=1).stack(level=1)

                     unemployment_rate  qty_unemployed  qty_employed  \
state   period year
Alabama M01    2000                5.1          108551       2024262
               2001                5.2          110035       2008876
               2002                6.5          134750       1953814
               2003                6.2          129966       1974374
               2004                6.4          134673       1985886
               2005                5.4          114319       2011219
               2006                4.4           93680       2048878
               2007                4.3           93046       2076252
               2008                4.8          104650       2065583
               2009                9.7          208908       1955196
               2010               12.3          263375       1871780
               2011               11.0          243001       1967127
               2012                8.3          177986       1973652
               2013                8.2          177887       1988180
               2014                7.5          162341       1989459
               2015                6.4          135842       1998388
               2016                6.3          134592       2007036
        M02    2000                5.1          109464       2027226
               2001                5.0          105469       2009904
               2002                6.3          132979       1966562
               2003                6.0          127265       1980206
               2004                6.1          130294       1990082
               2005                5.4          115837       2014928
               2006                4.5           96643       2053723
               2007                4.2           91769       2078300
               2008                4.9          106990       2060564
               2009               10.5          227822       1943707
               2010               12.1          258825       1876758
               2011               10.5          232117       1972720
               2012                8.4          182555       1982828
...                                ...             ...           ...
Wyoming M11    2004                3.7           10109        264755
               2005                3.5            9682        268258
               2006                3.0            8434        274556
               2007                2.6            7454        281477
               2008                3.2            9449        286241
               2009                6.7           20164        280411
               2010                6.1           18538        286846
               2011                5.6           17208        290964
               2012                5.2           15895        291053
               2013                4.4           13608        292991
               2014                4.1           12708        293710
               2015                4.5           13669        289223
               2016                4.6           13967        286447
        M12    2000                3.9           10373        256296
               2001                3.9           10512        256858
               2002                4.5           12019        257886
               2003                4.2           11431        261414
               2004                3.7           10114        262956
               2005                3.5            9808        266945
               2006                2.9            8165        273821
               2007                2.5            7310        279864
               2008                3.7           10963        283829
               2009                7.5           22395        278187
               2010                6.2           18913        285211
               2011                5.7           17602        289288
               2012                5.2           15953        289131
               2013                4.6           14116        291169
               2014                3.8           11613        292140
               2015                4.8           14459        286400
               2016                5.0           14866        284248

                     labour_force
state   period year
Alabama M01    2000       2132813
               2001       2118911
               2002       2088564
               2003       2104340
               2004       2120559
               2005       2125538
               2006       2142558
               2007       2169298
               2008       2170233
               2009       2164104
               2010       2135155
               2011       2210128
               2012       2151638
               2013       2166067
               2014       2151800
               2015       2134230
               2016       2141628
        M02    2000       2136690
               2001       2115373
               2002       2099541
               2003       2107471
               2004       2120376
               2005       2130765
               2006       2150366
               2007       2170069
               2008       2167554
               2009       2171529
               2010       2135583
               2011       2204837
               2012       2165383
...                           ...
Wyoming M11    2004        274864
               2005        277940
               2006        282990
               2007        288931
               2008        295690
               2009        300575
               2010        305384
               2011        308172
               2012        306948
               2013        306599
               2014        306418
               2015        302892
               2016        300414
        M12    2000        266669
               2001        267370
               2002        269905
               2003        272845
               2004        273070
               2005        276753
               2006        281986
               2007        287174
               2008        294792
               2009        300582
               2010        304124
               2011        306890
               2012        305084
               2013        305285
               2014        303753
               2015        300859
               2016        299114

[10608 rows x 4 columns]

In this way, the `unstack`-`stack` functionality is a useful way to view data and potentially see some patterns; even if the data is has high dimensionality in the index

### Challenge
* Use the unstack method to view data about the employment rate among the labor force over years and months in California